import cytoscape from "cytoscape";
import { useEffect, useRef, useState } from "react";
import { ReadWrite } from "../types/readWrite";
import { AggregateFunctions, GNN } from "./gnn";
import { Button, Dialog, DialogContent, MenuItem, Select, TextField } from "@mui/material";

function gnnToCyto(gnn: GNN){
	const gnnData: {data: {id: string}}[] = [];
	gnn.nodes.forEach((node, index) => {
		const nodeData = {data: {id: index.toString(), weight: node.weight, constant: node.constant, agg: AggregateFunctions[node.aggFun]}};
		gnnData.push(nodeData);
		if(index !== 0){
			const edgeData = {
				data: {
					id: index.toString().concat('e'.concat(index.toString())),
					source: (index - 1).toString(),
					target: index.toString()
				},
				selectable: false,
				style: {events: "no"}
			};
			gnnData.push(edgeData);
		}
	})
	return gnnData;
}

export default function GNNView(props: {gnn: ReadWrite<GNN>, selectedNode?: ReadWrite<number | null>}){
	const graphRef = useRef<HTMLDivElement>(null);
	const [dialogOpen, setDialogOpen] = useState<number|null>(null);
	const [dialogWeight, setDialogWeight] = useState(0);
	const [dialogConst, setDialogConst] = useState(0);
	const [dialogAggFun, setDialogAggFun] = useState(AggregateFunctions.mean)

	const dialogClose = () => {
		if(dialogOpen !== null){
			const newGNN = props.gnn.data.clone();
			newGNN.nodes[dialogOpen].weight = dialogWeight;
			newGNN.nodes[dialogOpen].constant = dialogConst;
			newGNN.nodes[dialogOpen].aggFun = dialogAggFun;
			setDialogOpen(null);
			props.gnn.setData(newGNN);
		}
	}

	useEffect(()=> {
		const cy = cytoscape({
			container: graphRef.current,
			elements: gnnToCyto(props.gnn.data),
			layout: {name: 'grid', rows: 1},
			userPanningEnabled: false,
			userZoomingEnabled: false,
			boxSelectionEnabled: false,
			autoungrabify: true,
			style: [
				{
					selector: 'node',
					style: {
						'label': (ele: any) => {return 'Layer ' + ele.data("id") + '\nWeight: ' + ele.data("weight") + '\nBias: ' + ele.data("constant")+ '\nAggregate Function: ' + ele.data("agg")},
						"text-wrap": "wrap",
						"shape": "rectangle"
					}
				},
				{
					selector: 'edge',
					style: {
						"curve-style": "bezier",
						"target-arrow-shape": "triangle"
					}
				}
			]
		});

		cy.fit();
		cy.nodes().on("dblclick ", (event)=> {
			setDialogOpen(parseInt(event.target.data("id")));
			setDialogConst(props.gnn.data.nodes[parseInt(event.target.data("id"))].constant);
			setDialogWeight(props.gnn.data.nodes[parseInt(event.target.data("id"))].weight);
			setDialogAggFun(props.gnn.data.nodes[parseInt(event.target.data("id"))].aggFun)
		});
		if(props.selectedNode !== undefined && props.selectedNode.data !== null){
			cy.$('#'.concat(props.selectedNode.data.toString())).select();
		}
		if(props.selectedNode !== undefined){
			const handleSelect: cytoscape.EventHandler = (e) => {
				props.selectedNode?.setData(parseInt(e.target.data("id")));
			}

			const handleUnselect = () => {
				props.selectedNode?.setData(null);
			}
	
			cy.on("select", handleSelect);
			cy.on("unselect", handleUnselect);
	
		}

	}, [props.gnn.data, props.selectedNode])
	return (
		<>
			<div>Click on a node to display the messages sent by nodes and the node embeddings generated by the layer. Double click on a selected node to edit the weight and bias.</div>
			<div style={{width: '100%', height: '100%'}} ref={graphRef}></div>
			<Dialog open={dialogOpen !== null} onClose={()=>{dialogClose}}>
				<DialogContent>
					{(dialogOpen !== null)?
						<>
							<div>
								<TextField type="number" label="Weight" value={dialogWeight} onChange={(e)=> {setDialogWeight(parseInt(e.target.value))}} />
							</div>
							<br />
							<div>
								<TextField type="number" label="Bias" value={dialogConst} onChange={(e)=> {setDialogConst(parseInt(e.target.value))}} />
							</div>
							<div>Aggregate function: 
								<Select value={AggregateFunctions[dialogAggFun]} label="Aggregate function" onChange={(e)=> {setDialogAggFun(AggregateFunctions[e.target.value as keyof typeof AggregateFunctions])}}>
									<MenuItem value={"mean"}>Mean</MenuItem>
									<MenuItem value={"min"}>Min</MenuItem>
									<MenuItem value={"max"}>Max</MenuItem>
									<MenuItem value={"sum"}>Sum</MenuItem>
								</Select>
							</div>
							<Button variant="outlined" onClick={dialogClose}>Ok</Button>
						</>
					:null}
				</DialogContent>
			</Dialog>
		</>
		
	)
}